spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello-world?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
